#line 2 "analyseur.lex.cpp"

#line 4 "analyseur.lex.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 39
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE machineextensionsanalyseurrestart(yyin ,yyscanner )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via machineextensionsanalyseurrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void machineextensionsanalyseurrestart (FILE *input_file ,yyscan_t yyscanner );
void machineextensionsanalyseur_switch_to_buffer (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
YY_BUFFER_STATE machineextensionsanalyseur_create_buffer (FILE *file,int size ,yyscan_t yyscanner );
void machineextensionsanalyseur_delete_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void machineextensionsanalyseur_flush_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void machineextensionsanalyseurpush_buffer_state (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
void machineextensionsanalyseurpop_buffer_state (yyscan_t yyscanner );

static void machineextensionsanalyseurensure_buffer_stack (yyscan_t yyscanner );
static void machineextensionsanalyseur_load_buffer_state (yyscan_t yyscanner );
static void machineextensionsanalyseur_init_buffer (YY_BUFFER_STATE b,FILE *file ,yyscan_t yyscanner );

#define YY_FLUSH_BUFFER machineextensionsanalyseur_flush_buffer(YY_CURRENT_BUFFER ,yyscanner)

YY_BUFFER_STATE machineextensionsanalyseur_scan_buffer (char *base,yy_size_t size ,yyscan_t yyscanner );
YY_BUFFER_STATE machineextensionsanalyseur_scan_string (yyconst char *yy_str ,yyscan_t yyscanner );
YY_BUFFER_STATE machineextensionsanalyseur_scan_bytes (yyconst char *bytes,yy_size_t len ,yyscan_t yyscanner );

void *machineextensionsanalyseuralloc (yy_size_t ,yyscan_t yyscanner );
void *machineextensionsanalyseurrealloc (void *,yy_size_t ,yyscan_t yyscanner );
void machineextensionsanalyseurfree (void * ,yyscan_t yyscanner );

#define yy_new_buffer machineextensionsanalyseur_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        machineextensionsanalyseurensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            machineextensionsanalyseur_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        machineextensionsanalyseurensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            machineextensionsanalyseur_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define machineextensionsanalyseurwrap(yyscanner) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state (yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  ,yyscan_t yyscanner);
static int yy_get_next_buffer (yyscan_t yyscanner );
static void yy_fatal_error (yyconst char msg[] ,yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 63
#define YY_END_OF_BUFFER 64
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[216] =
    {   0,
        0,    0,    0,    0,   64,   62,   59,   61,   62,   60,
       48,   62,   49,   50,   54,   53,   40,   62,   20,    1,
        1,   57,   41,   33,   42,   34,   55,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   51,   52,    2,   38,   56,   39,   61,   60,
       60,    0,   58,   19,    1,   35,   43,   37,   44,   36,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    2,   47,    0,    1,    0,    0,
       25,    0,    0,    0,   23,   30,    0,   27,    0,    0,

        0,    0,   29,    0,   26,    0,    0,   24,   28,    0,
        0,    4,    0,    0,    0,    1,    0,   31,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    6,    0,    0,    0,    1,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   22,    0,    0,    1,    0,    5,    0,    0,
        0,    0,   32,    0,   13,    0,    3,    0,    0,    8,
       16,    0,    0,    1,    0,    0,    0,    0,   45,   21,
        0,    0,    0,    0,   17,    1,   14,    9,    0,    0,
       18,    0,    0,   46,    1,   15,    0,    0,   11,   12,

        1,    0,    0,    1,    7,    0,    1,   10,    1,    1,
        1,    1,    1,    1,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    5,    6,    1,    1,    7,    8,
        9,   10,   11,   12,   13,   14,    1,   15,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   17,   18,   19,
       20,   21,   22,    1,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   33,   34,   35,   36,   37,   38,
       39,   40,   41,   42,   43,   44,   45,   32,   46,   32,
       47,    1,   48,    1,   49,    1,   50,   50,   50,   50,

       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   51,   52,   53,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[54] =
    {   0,
        1,    1,    2,    1,    1,    1,    3,    1,    1,    1,
        1,    1,    1,    1,    4,    4,    1,    1,    1,    1,
        5,    1,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    1,    1,    3,    5,
        1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[220] =
    {   0,
        0,    0,    0,    0,  254,  255,  255,  255,  250,  247,
      255,    0,  255,  255,  255,  255,  255,  230,  255,  255,
       39,  255,  255,   37,  229,  228,  255,   19,  214,  220,
      203,   24,  218,  213,   38,   25,   38,   41,  197,  201,
      218,  217,  255,  255,   55,  255,  255,  255,  255,  234,
      255,  231,  255,  255,   58,  255,  255,  255,  255,  255,
      208,  194,  199,  206,  197,   34,  193,  185,  206,  189,
      186,  185,  199,  187,  181,  183,  192,  182,  180,   43,
      181,  191,   45,  186,   73,  255,  209,   75,  172,  177,
      255,  182,  187,  169,  183,  255,  164,  255,  175,  184,

      175,  165,  255,  175,  255,  176,  159,  158,  255,  158,
      172,  255,  155,  166,  154,   77,  160,  255,  158,  151,
      152,  151,  153,  162,  164,  150,  146,  154,  158,  156,
      157,  154,  255,  153,  156,  147,   79,  150,  149,  144,
      131,  133,  132,  131,  136,  133,  137,  131,  123,  129,
      122,  128,  255,  138,  125,   81,  124,  255,  122,  133,
      114,  130,  255,  128,  255,  128,  255,  119,  127,  255,
      255,  117,  121,   83,  107,  112,  105,  108,  255,  255,
      118,  117,  116,  115,  255,   85,  100,  255,  109,   97,
      255,   98,   97,  255,   87,  255,   98,   94,  255,  255,

       91,   50,   45,   93,  255,   41,   95,  255,   97,   99,
      101,  103,  105,  255,  255,  123,   61,  126,  130
    } ;

static yyconst flex_int16_t yy_def[220] =
    {   0,
      215,    1,    1,    1,  215,  215,  215,  215,  215,  216,
      215,  217,  215,  215,  215,  215,  215,  218,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  216,
      215,  219,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  219,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,

      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,

      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,    0,  215,  215,  215,  215
    } ;

static yyconst flex_int16_t yy_nxt[309] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   14,   15,
       16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,    6,   30,    6,   31,    6,    6,
       32,    6,   33,   34,   35,    6,   36,   37,    6,    6,
       38,   39,   40,   41,   42,    6,   43,   44,    6,   45,
       46,   47,   48,   55,   55,   56,   57,   58,   61,   66,
       70,   62,   72,   67,   74,   77,   52,   78,   73,   85,
       85,   75,   88,   88,   94,   95,  208,  109,  113,   76,
       71,  206,   79,  110,  114,  205,   80,   85,   85,  116,
      116,  137,  137,  156,  156,  174,  174,  186,  186,  195,

      195,  201,  201,   85,   85,  204,  204,  207,  207,  209,
      209,  210,  210,  211,  211,  212,  212,  213,  213,  214,
      214,   85,   85,   50,  203,   50,   50,   50,   50,   53,
       53,   53,   87,   87,  202,   87,  200,  199,  198,  197,
      196,  194,  193,  192,  191,  190,  189,  188,  187,  185,
      184,  183,  182,  181,  180,  179,  178,  177,  176,  175,
      173,  172,  171,  170,  169,  168,  167,  166,  165,  164,
      163,  162,  161,  160,  159,  158,  157,  155,  154,  153,
      152,  151,  150,  149,  148,  147,  146,  145,  144,  143,
      142,  141,  140,  139,  138,  136,  135,  134,  133,  132,

      131,  130,  129,  128,  127,  126,  125,  124,  123,  122,
      121,  120,  119,  118,  117,   86,  115,  112,  111,  108,
      107,  106,  105,  104,  103,  102,  101,  100,   99,   98,
       97,   96,   93,   92,   91,   90,   89,   86,   51,   84,
       83,   82,   81,   69,   68,   65,   64,   63,   60,   59,
       54,   51,   49,  215,    5,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,

      215,  215,  215,  215,  215,  215,  215,  215
    } ;

static yyconst flex_int16_t yy_chk[309] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   21,   21,   24,   24,   24,   28,   32,
       35,   28,   36,   32,   37,   38,  217,   38,   36,   45,
       45,   37,   55,   55,   66,   66,  206,   80,   83,   37,
       35,  203,   38,   80,   83,  202,   38,   85,   85,   88,
       88,  116,  116,  137,  137,  156,  156,  174,  174,  186,

      186,  195,  195,   45,   45,  201,  201,  204,  204,  207,
      207,  209,  209,  210,  210,  211,  211,  212,  212,  213,
      213,   85,   85,  216,  198,  216,  216,  216,  216,  218,
      218,  218,  219,  219,  197,  219,  193,  192,  190,  189,
      187,  184,  183,  182,  181,  178,  177,  176,  175,  173,
      172,  169,  168,  166,  164,  162,  161,  160,  159,  157,
      155,  154,  152,  151,  150,  149,  148,  147,  146,  145,
      144,  143,  142,  141,  140,  139,  138,  136,  135,  134,
      132,  131,  130,  129,  128,  127,  126,  125,  124,  123,
      122,  121,  120,  119,  117,  115,  114,  113,  111,  110,

      108,  107,  106,  104,  102,  101,  100,   99,   97,   95,
       94,   93,   92,   90,   89,   87,   84,   82,   81,   79,
       78,   77,   76,   75,   74,   73,   72,   71,   70,   69,
       68,   67,   65,   64,   63,   62,   61,   52,   50,   42,
       41,   40,   39,   34,   33,   31,   30,   29,   26,   25,
       18,   10,    9,    5,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  215,  215,  215,  215,  215,  215,

      215,  215,  215,  215,  215,  215,  215,  215
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
/*
 * Simple Virtual Machine - A versatile and robust architecture to
 * easily write applications.
 * Copyright (C) 2021  Julien BRUGUIER
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
#line 21 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
#include <src/global/global.h>
#include <src/machine/extensions/analyseur/includes.h>

#define YY_USER_ACTION yylloc->first_line = yylloc->last_line;


#line 599 "analyseur.lex.cpp"

#define INITIAL 0
#define ISOLATION 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    yy_size_t yy_n_chars;
    yy_size_t yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    YYSTYPE * yylval_r;

    YYLTYPE * yylloc_r;

    }; /* end struct yyguts_t */

static int yy_init_globals (yyscan_t yyscanner );

    /* This must go here because YYSTYPE and YYLTYPE are included
     * from bison output in section 1.*/
    #    define yylval yyg->yylval_r
    
    #    define yylloc yyg->yylloc_r
    
int machineextensionsanalyseurlex_init (yyscan_t* scanner);

int machineextensionsanalyseurlex_init_extra (YY_EXTRA_TYPE user_defined,yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int machineextensionsanalyseurlex_destroy (yyscan_t yyscanner );

int machineextensionsanalyseurget_debug (yyscan_t yyscanner );

void machineextensionsanalyseurset_debug (int debug_flag ,yyscan_t yyscanner );

YY_EXTRA_TYPE machineextensionsanalyseurget_extra (yyscan_t yyscanner );

void machineextensionsanalyseurset_extra (YY_EXTRA_TYPE user_defined ,yyscan_t yyscanner );

FILE *machineextensionsanalyseurget_in (yyscan_t yyscanner );

void machineextensionsanalyseurset_in  (FILE * in_str ,yyscan_t yyscanner );

FILE *machineextensionsanalyseurget_out (yyscan_t yyscanner );

void machineextensionsanalyseurset_out  (FILE * out_str ,yyscan_t yyscanner );

yy_size_t machineextensionsanalyseurget_leng (yyscan_t yyscanner );

char *machineextensionsanalyseurget_text (yyscan_t yyscanner );

int machineextensionsanalyseurget_lineno (yyscan_t yyscanner );

void machineextensionsanalyseurset_lineno (int line_number ,yyscan_t yyscanner );

int machineextensionsanalyseurget_column  (yyscan_t yyscanner );

void machineextensionsanalyseurset_column (int column_no ,yyscan_t yyscanner );

YYSTYPE * machineextensionsanalyseurget_lval (yyscan_t yyscanner );

void machineextensionsanalyseurset_lval (YYSTYPE * yylval_param ,yyscan_t yyscanner );

       YYLTYPE *machineextensionsanalyseurget_lloc (yyscan_t yyscanner );
    
        void machineextensionsanalyseurset_lloc (YYLTYPE * yylloc_param ,yyscan_t yyscanner );
    
/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int machineextensionsanalyseurwrap (yyscan_t yyscanner );
#else
extern int machineextensionsanalyseurwrap (yyscan_t yyscanner );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int ,yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * ,yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (yyscan_t yyscanner );
#else
static int input (yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int machineextensionsanalyseurlex \
               (YYSTYPE * yylval_param,YYLTYPE * yylloc_param ,yyscan_t yyscanner);

#define YY_DECL int machineextensionsanalyseurlex \
               (YYSTYPE * yylval_param, YYLTYPE * yylloc_param , yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yylval = yylval_param;

    yylloc = yylloc_param;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			machineextensionsanalyseurensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				machineextensionsanalyseur_create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
		}

		machineextensionsanalyseur_load_buffer_state(yyscanner );
		}

	{
#line 37 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"

#line 876 "analyseur.lex.cpp"

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 216 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 255 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 38 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ yylval->entier = ::atoi(yytext); return ENTIER; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 39 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ yylval->chaine = std::string(yytext,yyleng); return IDENTIFIANT; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 40 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ return PLUGIN; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 41 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ return USE; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 42 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ return DEFINE; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 43 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ return TYPE; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 44 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ return INSTRUCTION; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 45 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ return STRUCT; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 46 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ return FUNCTION; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 47 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ return INTERRUPTION; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 48 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ return SCHEDULER; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 49 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ return SEQUENCER; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 50 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ return OPTION; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 51 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ return ARGUMENT; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 52 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ return ARGUMENTS; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 53 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ return SYSTEM; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 54 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ return WAITING; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 55 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ return OVERRIDE; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 56 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ return RETURN; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 57 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ return POINT; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 58 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ return MUTABLE; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 59 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ return VALUE; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 60 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ return INT; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 61 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ return STR; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 62 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ return BLN; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 63 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ return PTR; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 64 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ return LIB; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 65 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ return SYM; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 66 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ return PEP; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 67 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ return IRQ; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 68 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ return AUTO; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 69 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ return MARKER; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 70 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ return INFERIEUR; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 71 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ return SUPERIEUR; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 72 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ return INFERIEUR_INFERIEUR; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 73 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ return SUPERIEUR_SUPERIEUR; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 74 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ return INFERIEUR_SUPERIEUR; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 75 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ return DEBUT_ACCOLADE; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 76 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ return FIN_ACCOLADE; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 77 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ return VIRGULE; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 78 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ return POINT_VIRGULE; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 79 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ return EGAL; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 80 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ return INFERIEUR_OU_EGAL; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 81 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ return SUPERIEUR_OU_EGAL; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 82 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ return KEYWORD; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 83 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ return VARIABLE; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 84 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ std::string token(yytext,yyleng); yylval->chaine = token.substr(1,token.size()-2); return MOT_CLEF; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 85 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ return STRUCTURE; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 86 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ return DEBUT_PARENTHESE; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 87 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ return FIN_PARENTHESE; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 88 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ return DEBUT_CROCHET; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 89 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ return FIN_CROCHET; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 90 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ return PLUS; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 91 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ return FOIS; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 92 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ return POINT_INTERROGATION; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 93 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ return ALTERNATIVE; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 94 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ return DEUX_POINTS; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 95 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ std::string token(yytext,yyleng); yylval->chaine = token.substr(1); return VALEUR_OPTION; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 96 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 97 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ return FIN_LIGNE; }
	YY_BREAK
case 61:
/* rule 61 can match eol */
YY_RULE_SETUP
#line 98 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ ++yylloc->last_line; /* nouvelle ligne */ BEGIN(INITIAL); return FIN_LIGNE; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 99 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
{ return _INVALIDE_; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 100 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"
ECHO;
	YY_BREAK
#line 1249 "analyseur.lex.cpp"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(ISOLATION):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * machineextensionsanalyseurlex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( machineextensionsanalyseurwrap(yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of machineextensionsanalyseurlex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = yyg->yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					machineextensionsanalyseurrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2 ,yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			machineextensionsanalyseurrestart(yyin  ,yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) (yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) machineextensionsanalyseurrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size ,yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 216 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	register int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	register char *yy_cp = yyg->yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 216 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 215);

	(void)yyg;
	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yy_size_t offset = yyg->yy_c_buf_p - yyg->yytext_ptr;
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					machineextensionsanalyseurrestart(yyin ,yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( machineextensionsanalyseurwrap(yyscanner ) )
						return EOF;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void machineextensionsanalyseurrestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        machineextensionsanalyseurensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            machineextensionsanalyseur_create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
	}

	machineextensionsanalyseur_init_buffer(YY_CURRENT_BUFFER,input_file ,yyscanner);
	machineextensionsanalyseur_load_buffer_state(yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void machineextensionsanalyseur_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		machineextensionsanalyseurpop_buffer_state();
	 *		machineextensionsanalyseurpush_buffer_state(new_buffer);
     */
	machineextensionsanalyseurensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	machineextensionsanalyseur_load_buffer_state(yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (machineextensionsanalyseurwrap()) processing, but the only time this flag
	 * is looked at is after machineextensionsanalyseurwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void machineextensionsanalyseur_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE machineextensionsanalyseur_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) machineextensionsanalyseuralloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in machineextensionsanalyseur_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) machineextensionsanalyseuralloc(b->yy_buf_size + 2 ,yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in machineextensionsanalyseur_create_buffer()" );

	b->yy_is_our_buffer = 1;

	machineextensionsanalyseur_init_buffer(b,file ,yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with machineextensionsanalyseur_create_buffer()
 * @param yyscanner The scanner object.
 */
    void machineextensionsanalyseur_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		machineextensionsanalyseurfree((void *) b->yy_ch_buf ,yyscanner );

	machineextensionsanalyseurfree((void *) b ,yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a machineextensionsanalyseurrestart() or at EOF.
 */
    static void machineextensionsanalyseur_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	machineextensionsanalyseur_flush_buffer(b ,yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then machineextensionsanalyseur_init_buffer was _probably_
     * called from machineextensionsanalyseurrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void machineextensionsanalyseur_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		machineextensionsanalyseur_load_buffer_state(yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void machineextensionsanalyseurpush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	machineextensionsanalyseurensure_buffer_stack(yyscanner);

	/* This block is copied from machineextensionsanalyseur_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from machineextensionsanalyseur_switch_to_buffer. */
	machineextensionsanalyseur_load_buffer_state(yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void machineextensionsanalyseurpop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	machineextensionsanalyseur_delete_buffer(YY_CURRENT_BUFFER ,yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		machineextensionsanalyseur_load_buffer_state(yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void machineextensionsanalyseurensure_buffer_stack (yyscan_t yyscanner)
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)machineextensionsanalyseuralloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in machineextensionsanalyseurensure_buffer_stack()" );
								  
		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)machineextensionsanalyseurrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in machineextensionsanalyseurensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE machineextensionsanalyseur_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) machineextensionsanalyseuralloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in machineextensionsanalyseur_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	machineextensionsanalyseur_switch_to_buffer(b ,yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to machineextensionsanalyseurlex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       machineextensionsanalyseur_scan_bytes() instead.
 */
YY_BUFFER_STATE machineextensionsanalyseur_scan_string (yyconst char * yystr , yyscan_t yyscanner)
{
    
	return machineextensionsanalyseur_scan_bytes(yystr,strlen(yystr) ,yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to machineextensionsanalyseurlex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE machineextensionsanalyseur_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) machineextensionsanalyseuralloc(n ,yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in machineextensionsanalyseur_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = machineextensionsanalyseur_scan_buffer(buf,n ,yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in machineextensionsanalyseur_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg , yyscan_t yyscanner)
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE machineextensionsanalyseurget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int machineextensionsanalyseurget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int machineextensionsanalyseurget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *machineextensionsanalyseurget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *machineextensionsanalyseurget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
yy_size_t machineextensionsanalyseurget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *machineextensionsanalyseurget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void machineextensionsanalyseurset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void machineextensionsanalyseurset_lineno (int  line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "machineextensionsanalyseurset_lineno called with no buffer" );
    
    yylineno = line_number;
}

/** Set the current column.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void machineextensionsanalyseurset_column (int  column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "machineextensionsanalyseurset_column called with no buffer" );
    
    yycolumn = column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see machineextensionsanalyseur_switch_to_buffer
 */
void machineextensionsanalyseurset_in (FILE *  in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = in_str ;
}

void machineextensionsanalyseurset_out (FILE *  out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = out_str ;
}

int machineextensionsanalyseurget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void machineextensionsanalyseurset_debug (int  bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = bdebug ;
}

/* Accessor methods for yylval and yylloc */

YYSTYPE * machineextensionsanalyseurget_lval  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylval;
}

void machineextensionsanalyseurset_lval (YYSTYPE *  yylval_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylval = yylval_param;
}

YYLTYPE *machineextensionsanalyseurget_lloc  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylloc;
}
    
void machineextensionsanalyseurset_lloc (YYLTYPE *  yylloc_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylloc = yylloc_param;
}
    
/* User-visible API */

/* machineextensionsanalyseurlex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */

int machineextensionsanalyseurlex_init(yyscan_t* ptr_yy_globals)

{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) machineextensionsanalyseuralloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* machineextensionsanalyseurlex_init_extra has the same functionality as machineextensionsanalyseurlex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to machineextensionsanalyseuralloc in
 * the yyextra field.
 */

int machineextensionsanalyseurlex_init_extra(YY_EXTRA_TYPE yy_user_defined,yyscan_t* ptr_yy_globals )

{
    struct yyguts_t dummy_yyguts;

    machineextensionsanalyseurset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }
	
    *ptr_yy_globals = (yyscan_t) machineextensionsanalyseuralloc ( sizeof( struct yyguts_t ), &dummy_yyguts );
	
    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }
    
    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));
    
    machineextensionsanalyseurset_extra (yy_user_defined, *ptr_yy_globals);
    
    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from machineextensionsanalyseurlex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = 0;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = (char *) 0;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * machineextensionsanalyseurlex_init()
     */
    return 0;
}

/* machineextensionsanalyseurlex_destroy is for both reentrant and non-reentrant scanners. */
int machineextensionsanalyseurlex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		machineextensionsanalyseur_delete_buffer(YY_CURRENT_BUFFER ,yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		machineextensionsanalyseurpop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	machineextensionsanalyseurfree(yyg->yy_buffer_stack ,yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        machineextensionsanalyseurfree(yyg->yy_start_stack ,yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * machineextensionsanalyseurlex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    machineextensionsanalyseurfree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n , yyscan_t yyscanner)
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s , yyscan_t yyscanner)
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *machineextensionsanalyseuralloc (yy_size_t  size , yyscan_t yyscanner)
{
	return (void *) malloc( size );
}

void *machineextensionsanalyseurrealloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void machineextensionsanalyseurfree (void * ptr , yyscan_t yyscanner)
{
	free( (char *) ptr );	/* see machineextensionsanalyseurrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 100 "/home/pappy/Programmation/svm/projet/src/machine/extensions/analyseur/analyseur.lex.lpp"



